### ISSUE TITLE
Package name of  GithubRepositoryImpl class is wrong

### ISSUE THREAD

**Issue by Redman1037** [florent37/KotlinNativeSample#1]
Package name of  GithubRepositoryImpl class is `org.jetbrains.kotlinconf.model`  instead of `org.jetbrains.kotlinconf.data` . Is it a mistake or did you do it on purpose ? .

Also app runs fine but every thing related to common folder showing in red color(Unresolved reference) in android studio .

**Comment by florent37** [comment]
Yes i did bit had the Time to change it

Le ven. 2 nov. 2018 à 08:15, Manohar Reddy <notifications@github.com> a
écrit :

**Comment by florent37** [comment]
I did not had Time to change it
